### ISSUE TITLE
help, flac is downloaded up to 76% and starts to postprocess and gives me an error

### ISSUE THREAD

**Issue by fabriccioguzman** [TripleFrequency/AthamePlugin.Deezer#30] opened 2017-12-06 23:14 UTC
help, flac is downloaded up to 76% and starts to postprocess and gives me an error and the file is named like this 4 Symphony No. 5 in C major, Op. 67- IV. Allegro.flac-temp and weigh 0 bytes

http://www.deezer.com/es/track/6314122

[2017-12-06T00:34:04.9575148-05:00] [Warning] MainForm: Adding non-downloadable track Deezer/118600328
[2017-12-06T17:15:42.4093960-05:00] [Error] MainForm: MDQ exception handler
CorruptFileException: FLAC stream not found at starting position.
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Athame.DownloadAndTag.TrackTagger.Write(String serviceName, Track completedTrack, TrackFile trackFile, AlbumArtworkSaveFormat saveFormat, String path)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__32.MoveNext()
[2017-12-06T18:05:19.4976757-05:00] [Error] MainForm: MDQ exception handler
CorruptFileException: FLAC stream not found at starting position.
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Athame.DownloadAndTag.TrackTagger.Write(String serviceName, Track completedTrack, TrackFile trackFile, AlbumArtworkSaveFormat saveFormat, String path)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__32.MoveNext()

**Comment by TripleFrequency** [comment] 2017-12-07 01:27
Very interesting. This sounds like a duplicate of #25, which will hopefully be fixed in the next release. Could you verify that re-downloading it works or not?

**Comment by redreadnut** [comment] 2017-12-07 01:32
Just downloaded this track without any problem.
Guzman, maybe your HDD is out of free space? Guzman, don't take too much, don't try to download the whole Internet :D

**Comment by bascurtiz** [comment] 2017-12-07 01:33
All good here, 100% d/led, see pic:
https://gyazo.com/949996de332ab4f5d2513ee062121ac8

**Comment by jonaaa20** [comment] 2017-12-07 01:50
No problems here too.

**Closed** 2017-12-08 23:46 UTC
