### ISSUE TITLE
available tracks in other albums.

### ISSUE THREAD

**Issue by Refelinux** [TripleFrequency/AthamePlugin.Deezer#20] opened 2017-12-03 12:15 UTC
In deezer many albums that do not have all the tracks in the album, but the same tracks are taken from another album. Your script can not download them with required album. As in this. Tracks 4 & 5. http://www.deezer.com/ru/album/52253192

http://www.deezer.com/ru/album/51570712 - Also, for example, this album can not be added for downloading - probably because of the symbol "í" in the 10th track

P.S. also i must request covers 1200x1200, but it depends on your desire.

Addition: There is also no disc number in the tags, this is important if the album has more than one disc.

Thanks for your work !

**Comment by TripleFrequency** [comment] 2017-12-03 16:33
Your issue seems to be a duplicate of #3. Some tracks do not download for seemingly no reason, but reading your post gave me an idea which lead to fixing this issue. It will be fixed in the next release. I'll go into more detail in the comments of #3.

As for the request of bigger covers, since multiple people have asked for it, I will work on this next.

Also, there should be a disc number in the tags. Could you provide more info? One solution (my preferred one) is to use the {TrackNumber} path tag in the main Athame application.

**Comment by Refelinux** [comment] 2017-12-03 17:27
for example - this albums have 2CD - http://www.deezer.com/ru/album/6425567
Athame recognizes that there are 2 discs in the album, but after downloading in the folder the tracklist will be confused. I can not easily change this with the help of a program for tags, because there is no disc number in the tags.

**Comment by TripleFrequency** [comment] 2017-12-03 17:35
If you have multiple Discs, again I can't do anything about this. There is also a tag for Athame called {DiscNumber}. So you could set your path format to be something like this: "{AlbumArtistOrArtist}/{Album.Title}/{DiscNumber}-{TrackNumber} - {Title}"

**Closed by TripleFrequency** 2017-12-03 17:35 UTC
