### ISSUE TITLE
The same previous problem with tracks from other albums (A4.1)

### ISSUE THREAD

**Issue by Refelinux** [TripleFrequency/AthamePlugin.Deezer#31] opened 2017-12-08 08:50 UTC
Again the same previous problem with tracks from other albums (A4.1) as from this topic -
 https://github.com/TripleFrequency/AthamePlugin.Deezer/issues/20

**Comment by TripleFrequency** [comment] 2017-12-08 23:46
If this is a duplicate of #20, then the response would still stand that I can't do anything about this inside the plugin, you just have to modify your save path to include the disc number.

**Closed by TripleFrequency** 2017-12-08 23:46 UTC

**Comment by Refelinux** [comment] 2017-12-09 01:01
You did not understand me ! I'm talking about the first problem. Previously, it was not possible to download tracks that were available from other albums. You fixed it, but in version 1.3 this problem returned.

**Comment by TripleFrequency** [comment] 2017-12-09 15:52
Oh, I understand now. I didn't change how tracks are selected, so this is probably a more general issue with A4.1. As I mention in the release notes, it has a lot of problems with it, so only use it for testing. A3 should be much more stable.
