### ISSUE TITLE
Randomly  stops downloading (restarting Athame fixes it)

### ISSUE THREAD

**Issue by kannibleklown** [TripleFrequency/AthamePlugin.Deezer#12] opened 2017-12-02 09:54 UTC
Occasionaly my downloads will stop at this point, and all that happens is the song it is downloading flickers and just doesn't continue. After restarting Athame once or twice, it generally starts working again.

https://i.imgur.com/guhOiTZ.png

**Comment by TripleFrequency** [comment] 2017-12-02 10:35
I will explore this issue more when I get the chance. If you could continue to comment with albums this happens on, I would greatly appreciate it.

**Comment by kannibleklown** [comment] 2017-12-02 10:36
For sure, i'll start writing down the ones it happens with.

**Comment by kannibleklown** [comment] 2017-12-02 10:55
I'm not too sure it's based on the album, I downloaded one, it happened, then to test it I deleted the folder and re-downloaded. It had no issue the second time. I'll continue to write down the albums just in case tho.

**Comment by kannibleklown** [comment] 2017-12-02 12:25
Done downloading for now. Downloaded a total of 35 albums, with 15 of them I had issues with.
http://www.deezer.com/en/album/51659952
http://www.deezer.com/en/album/344622
http://www.deezer.com/en/album/51745572
http://www.deezer.com/en/album/6003145
http://www.deezer.com/en/album/6227078
http://www.deezer.com/en/album/1648461
http://www.deezer.com/en/album/1648459
http://www.deezer.com/en/album/1648480
http://www.deezer.com/en/album/1632597
http://www.deezer.com/en/album/1648495
http://www.deezer.com/en/album/1648469
http://www.deezer.com/en/album/7835707
http://www.deezer.com/en/album/49810472
http://www.deezer.com/en/album/1649535
http://www.deezer.com/en/album/6497331

**Comment by jonaaa20** [comment] 2017-12-02 12:47
This happens with the deezer downloader script too, that's a issue with deezer servers, i'm having this problem with all deezer downloaders out there.

**Comment by kannibleklown** [comment] 2017-12-02 22:29
If that's the case, would it be possible to have something like an auto-time out or auto refresh if it detects it has stopped or something alone those lines?

**Comment by TripleFrequency** [comment] 2017-12-02 22:51
I will be looking into this more. I haven't really used the plugin much, but I will try to reproduce this. It could be related to #3.

**Comment by fabriccioguzman** [comment] 2017-12-03 00:19
[2017-12-02T19:17:24.4248921-05:00] [Error] MainForm: MDQ exception handler
ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at System.IO.MemoryStream..ctor(Byte[] buffer)
   at AthamePlugin.Deezer.DeezerEncryptedDownloader.<>c__DisplayClass10_0.<DownloadAsyncTask>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AthamePlugin.Deezer.DeezerEncryptedDownloader.<DownloadAsyncTask>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__32.MoveNext()

**Comment by TripleFrequency** [comment] 2017-12-03 00:51
Interesting. Is this after you waited for a while? I am currently working on a solution to this problem.

The general idea being that if the download of the file doesn't progress for more than 10 seconds, the download will restart.

**Comment by jonaaa20** [comment] 2017-12-03 02:39
Would be nice if you add a "download monitor" like this:

If the download speed of a song doesn' reach 100kb/s in 10 seconds, restart the download or something similar, should 'fix' it.

**Comment by TripleFrequency** [comment] 2017-12-03 02:57
The download system I use inside the plugin already reports to Athame when the download state changes. So, when a download starts, I start a timer. If it reaches more than a minute without reporting a change in progress, then the plugin will attempt to download the track again.

The current issue I have is that it seems to break the Athame download queue, so I am currently working on that.

**Comment by TripleFrequency** [comment] 2017-12-03 03:24
@jonaaa20 A new pre-release with the fix for this issue has been posted. Please post any issues you have with it in this issue.

**Comment by TripleFrequency** [comment] 2017-12-03 03:26
@fabriccioguzman Do you have additional information about your issue? Or could you post a link to the track/album you were downloading?

**Comment by TripleFrequency** [comment] 2017-12-03 03:48
It isn't the same issue, unfortunately. His issue is that Athame begins downloading a singular song, then never stops. It's like it is infinitely downloading. Your issue seems to imply that it *finishes* downloading, but actually downloads nothing. "Buffer cannot be null" seems to imply that no information was actually downloaded. Based on that, I think I know where your issue was occurring, and created a new version of the pre-release. Version 1.2.7 - RC2 fixes the issue you encountered.

**Comment by fabriccioguzman** [comment] 2017-12-03 06:13
Sorry I did not know I thought it was the same problem, because @kannibleklown did not publish any detailed log or info thank you for fixing it

**Comment by TripleFrequency** [comment] 2017-12-03 14:24
@jonaaa20 I meant to address your solution earlier, as well. I didn't want to base it solely on the download *speed* because that could cause issues for people who have slow internet. The time-based solution was the simplest, without excluding people with slow network connections.

The only accurate way I could do it based on speed is calculate an average download speed for previous downloads, then restart a download if goes well below that average for a certain amount of time.

Now that I talk about it, it actually seems like an interesting solution 😄 .

**Comment by jonaaa20** [comment] 2017-12-03 14:29
Indeed, that would be painful for those that have slow internet, bit tour solution is working fine here, will report if i deal with the problem again, what about you? Having this issue too?

**Comment by TripleFrequency** [comment] 2017-12-03 14:31
Since the new release, no. I had it a couple times *before*, though.

**Comment by jonaaa20** [comment] 2017-12-03 14:35
Great, seems that your method is really effective, no need for this "download speed monitor" xD

**Closed** 2017-12-03 21:57 UTC
Labels: bug, help wanted
